[package]
name = "stignore-manager"
version = "0.0.1"
edition = "2021"
authors = ["Michael Robbins"]

[dependencies]
axum = { version="0.7", features=["macros"] }
axum-template = { version = "2.3", features=["tera"] }
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.37", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1"
toml = "0.8.13"
tera = "1.20.0"
tower-http = { version="0.5.2" , features=["fs"]}
reqwest = { version = "0.12.4", features = ["json"] }