[package]
name = "stignore-manager"
version = "0.0.1"
edition = "2021"
authors = ["Michael Robbins"]

[dependencies]
axum = { version="0.7.5", features=["macros"] }
axum-template = { version = "2.2.0", features=["tera"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
toml = "0.8.12"
tera = "1.19.1"
tower-http = { version="0.5.2" , features=["fs"]}